Output .github/preview.gif

Require tfx

Set Framerate 60
Set FontSize 30

Set Padding 20

Set Width 1800
Set Height 800

Set TypingSpeed 200ms

Hide
Type@1ms "cd tests/s3 && clear"
Enter
Show

Type "terraform show -json | tfx"

Sleep 1s
Enter
Sleep 3s

Enter
Sleep 2s

Down@400ms 10
Sleep 2s
Enter
Sleep 2s

Down
Sleep 2s
Enter
Sleep 2s
Down@500ms 2
Enter
Sleep 4s

Up@500ms 3
Sleep 2s
Backspace
Sleep 2s

Type "q"
Sleep 4s